---

- name: Create application directory
  file:
    path: "{{ application_directory }}"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}"

- name: Copy docker-compose file
  template:
    src: templates/docker-compose.yml
    dest: "{{ application_directory }}/docker-compose.yml"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
  notify: Restart docker compose

- name: Pull docker image Back-office madu
  docker_image:
    pull: yes
    name: "{{ application_backoffice_image }}:{{ application_backoffice_tag }}"
    force_source: yes
  notify: Restart docker compose

- name: Pull docker image App madu
  docker_image:
    pull: yes
    name: "{{ application_app_image }}:{{ application_app_tag }}"
    force_source: yes
  notify: Restart docker compose

- name: Start docker compose
  docker_compose:
    project_src: "{{ application_directory }}"