version: "3"

services:
  api:
    image: "{{ application_api_image }}:{{ application_api_tag }}"
    restart: always
    working_dir: /app
    depends_on:
      - prisma
    ports: 
      - "{{ application_api_port }}:3000"
    environment: 
      PORT: "{{ application_api_port }}"
      FRONT_URL: "{{ application_scheme }}://{{ back_office_ip }}"
      DATABASE_IP: "{{ database_ip }}"
      MONGO_INITDB_ROOT_USERNAME: "{{ MONGO_INITDB_ROOT_USERNAME }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ MONGO_INITDB_ROOT_PASSWORD }}"
      PRISMA_SECRET: "{{ PRISMA_SECRET }}"
      STRIPE_SECRET_KEY: "{{ STRIPE_SECRET_KEY }}"
      APP_SECRET: "{{ APP_SECRET }}"
      AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
      AWS_S3_BUCKET: "{{ AWS_S3_BUCKET }}"
      GOOGLE_MAPS_API_KEY: "{{ GOOGLE_MAPS_API_KEY }}"
    entrypoint: /app/entrypoint.sh
    command: yarn start

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "{{ application_prisma_port }}:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://{{ MONGO_INITDB_ROOT_USERNAME }}:{{ MONGO_INITDB_ROOT_PASSWORD }}@{{ database_ip }}
            port: 27017
