docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"

application_scheme: http

application_api_image: "{{ docker_username }}/madu_api"
application_api_tag: latest
application_api_port: 3000

application_backoffice_image: "{{ docker_username }}/madu_back-office"
application_backoffice_tag: latest
application_backoffice_port: 80


application_user: ubuntu
application_group: "{{ application_user }}"
application_directory: "/home/{{ application_user }}/app"

MONGO_INITDB_ROOT_USERNAME: "{{ lookup('env', 'MONGO_INITDB_ROOT_USERNAME') }}"
MONGO_INITDB_ROOT_PASSWORD: "{{ lookup('env', 'MONGO_INITDB_ROOT_PASSWORD') }}"
PRISMA_SECRET: "{{ lookup('env', 'PRISMA_SECRET') }}"

STRIPE_SECRET_KEY: "{{ lookup('env', 'STRIPE_SECRET_KEY') }}"
APP_SECRET: "{{ lookup('env', 'APP_SECRET') }}"
AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
AWS_S3_BUCKET: "{{ lookup('env', 'AWS_S3_BUCKET') }}"
GOOGLE_MAPS_API_KEY: "{{ lookup('env', 'GOOGLE_MAPS_API_KEY') }}"
